# Generated by Django 4.2.6 on 2023-11-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatura',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
