# Generated by Django 4.2.7 on 2023-11-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0002_alter_temperatura_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proximidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=90)),
            ],
        ),
    ]
